#!/bin/bash
echo "the userid $USERID"
[[ -z $USERID ]] && USERID="33"
echo $USERID
# Check to see if dir is empty or not
cd /var/www/html && [[ ! $(ls -A) ]] && git clone https://github.com/isntall/Lychee.git .
chown -R $USERID:www-data . && chmod -R 775 .

# Start Apache
source /etc/apache2/envvars
exec apache2 -D FOREGROUND
