#!/bin/bash

# Check to see if dir is empty or not
cd /var/www/html && [ ! $(ls -A) ] && https://github.com/isntall/Lychee.git . && chown -R www-data:www-data .

# Start Apache
source /etc/apache2/envvars
exec apache2 -D FOREGROUND
