#!/bin/bash

[[ -z $USERID ]] && USERID=33

# Check to see if dir is empty or not
cd /var/www/html && [[ ! $(ls -A) ]] && git clone -b docker-compose_fpm https://github.com/isntall/Lychee.git .
chown -R $USERID:www-data .
chmod -R 775 .
# Start php-fpm
php-fpm
